version: "3.9"

services:
  proxy:
    build: ./ha-proxy
    env_file: .env
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - ha_net

  web:
    build: .
    container_name: home-app
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - ha_net

  pocketbase:
    build: ./pocketbase
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_public:/pb/pb_public
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    restart: unless-stopped
    networks:
      - ha_net

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped
    networks:
      - ha_net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "admin"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

networks:
  ha_net:
    driver: bridge
